[UnityDoorstop]
# Enabled or disabled Unity Doorstop
enabled = true

# Target assembly (DLL) to load and execute
targetAssembly = melonloader.dll

# Redirect entry point to Doorstop
redirectEntry = true

# Additional DLLs to load
additionalAssemblies = version.dll

# Unity backend to use (auto, mono, il2cpp)
unityBackend = auto

# Enable debug logging
debug = false

# Log level (0=None, 1=Error, 2=Warning, 3=Info, 4=Debug)
logLevel = 2

# Log file path
logPath = doorstop.log
